# Generated by Django 6.0.6 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('RENT', 'Rent & Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel & Transport'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
